### ISSUE TITLE
Missing tag rpm-5_4_17

### ISSUE THREAD

**Issue by redbrain17** [azat-archive/popt#1]
Since the upstream http://rpm5.org site is down forever. It seems that this page is one of the few existing git mirrors. I have here a PKGBUILD file which is refering to a tag rpm-5_4_17-release.
Do you now where I can find rpm-5_4_17-release?

**Comment by azat** [comment]
No, initially I got this from [debian](https://packages.debian.org/search?keywords=libpopt-dev), and it has version `1.16` now, so I guess 5.14.17 is something rpm specific stuff.
